### ISSUE TITLE
[solved] Source install on 18.04

### ISSUE THREAD

**Issue by tylerjw** [colcon/colcon-common-extensions#12]
For simplicity of CI config reasons I'd like to use colcon in the same way on 18.04 as I am on 20.04.  I've been trying to use the pip based source install but it seems that it is missing some features (specifically the mixin verb and argument to build).  I'm not sure what I'm doing wrong.

Note that I first tried using colcon via the debian packages and it is missing the mixin feature there too.

I discovered there is a package python3-colcon-mixin that I needed.  However, now after trying to update mixin I don't have any available (`colcon mixin list` shows nothing).

```
$ colcon mixin show build
Passed verb name 'build' has no mixins
```

In case anyone else finds this in the future this is what I needed to do:

```
sudo apt install python3-colcon-mixin
colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
colcon mixin update default
```

**Comment by dirk-thomas** [comment]
> In case anyone else finds this in the future this is what I needed to do:

Just for the record: these steps are also documented in the README of the [colcon-mixin-repository](https://github.com/colcon/colcon-mixin-repository).
