### ISSUE TITLE
Release to PyPI

### ISSUE THREAD

**Issue by cottsay** [colcon/colcon-common-extensions#16]
Hello @dirk-thomas, could you please grant me (or someone else) the necessary privileges to release this package to PyPI?

**Comment by cottsay** [comment]
@dirk-thomas friendly ping.

**Comment by cottsay** [comment]
Hi @dirk-thomas, since the changes staged for release in this package will not change the default behavior for pip-based installs but will change the default behavior of debian-based installs, I'm going to release the package on Package Cloud only.

When you have time, please grant me (or someone else) privileges to upload the release to PyPI.

**Comment by dirk-thomas** [comment]
Sorry, I don't read GitHub notifications anymore on a regular basis.

> When you have time, please grant me (or someone else) privileges to upload the release to PyPI.

Done! Happy :ship:-ing.
