### ISSUE TITLE
Pinned versions

### ISSUE THREAD

**Issue by paulbovbel** [colcon/colcon-common-extensions#6]
It would be great if tagged releases of colcon-common-extensions (pypi and/or deb) had pinned versions of colcon components, so it would be possible to install a consistent 'older' version of colcon.

**Comment by dirk-thomas** [comment]
The goal of this package was to make it easy to install a common set of extensions. This would require releasing a new version of this package whenever either of the dependencies changes.

You should be able to create a `requirements.txt` file if you have a need to version-lock a set of packages.

I am not sure if it is worth the effort to provide this feature through this package...

**Comment by paulbovbel** [comment]
Fair enough. It's a bit tricky to find a 'consistent' set of versions, but I suppose the key is to do it when everything works.

**Comment by dirk-thomas** [comment]
> It's a bit tricky to find a 'consistent' set of versions

What cases are you referring to? When a package requires a specific minimum version (due to e.g. new API) it should declare that already. If there are specific cases where there are problems we should figure out why that is the case and if we can do something better.

**Comment by paulbovbel** [comment]
When trying to determine if https://github.com/colcon/colcon-ros/issues/35 was expected or a regression, I had the thought that 'wouldn't it be great to install `colcon` from two weeks ago?', especially given that it wasn't immediately clear which colcon package a regression could be in.

I understand that packages declare minimum versions for compatibility reasons, but from a usage point of view, it would be great if there was a periodic 'snapshot' across the many, many colcon components, that could be referenced as a single atomic release.

For now, I'll stick to pinning all my colcon component versions and periodically bumping them to see if anything breaks, which seems to be the python philosophy.
